apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: super-coworking
  name: super-coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: super-coworking
  template:
    metadata:
      labels:
        service: super-coworking
    spec:
      containers:
        - image: 939652184899.dkr.ecr.us-east-1.amazonaws.com/super-prj3:latest
          name: super-coworking
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
      restartPolicy: Always
